#!/usr/bin/bash

clear

test_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

nvim \
	--headless \
	--noplugin \
	-u "${test_dir}/mininit.lua" \
	-c "lua require('plenary.test_harness').test_directory('${test_dir}/', {sequential=true, keep_going=false})"

echo
